### ISSUE TITLE
Testing assignment invitations

### ISSUE THREAD

**Issue by ksuderman** [education/teachers#46]
We have an organization for our compilers course [1] and I have set up a classroom and one assignment with some starter code.  I would like to see what the students are going to see when they accept the invitation to the assignment [2], but when I follow the invitation link and click the `Accept this assignment` button I get the error:

```
Cannot retrieve this organizations repo plan, please reauthenticate your token. 
```
But I am not sure what token I am supposed to be reauthenticating?  My own?  The organizations?  How do I "reauthenticate my token"?

Thanks,
Keith

1. https://github.com/vassar-cmpu-331/
2. https://classroom.github.com/assignment-invitations/9a1aab67fe979eb4fadae025793460f9

**Comment by khatchad** [comment]
My class was also seeing this error today as well.

https://github.com/cst4713-d766 <https://github.com/cst4713-d766>
https://classroom.github.com/classrooms/16441572-cst-4713-dynamic-web-development-servlets-and-jsp-sp2016/assignments/projectzero <https://classroom.github.com/classrooms/16441572-cst-4713-dynamic-web-development-servlets-and-jsp-sp2016/assignments/projectzero>

**Comment by tarebyte** [comment]
@ksuderman if you sign out and sign back in that should fix it. If not please ping me and I can help you get it sorted out.

**Comment by khatchad** [comment]
Hi @ksuderman, I had students sign out and back in again and still experienced this problem. Can you help?

**Comment by tarebyte** [comment]
@khatchad did you by chance test to make sure your assignment worked correctly?

**Comment by khatchad** [comment]
@tarebyte Yes. I think I see the problem. As the student repositories are not forked, they are counting against my private repo limit.

**Comment by tarebyte** [comment]
@khatchad it should be counting against the organizations private repo limit.

**Comment by khatchad** [comment]
But forks don't count against the limit, I don't think.

**Comment by khatchad** [comment]
@tarebyte I only have 10 private repos but 24 students. That means I won't have enough repos even for one assignment.

**Comment by tarebyte** [comment]
@khatchad did you request private repos from education.github.com?

**Comment by khatchad** [comment]
@tarebyte Yes.

**Comment by khatchad** [comment]
@tarebyte As such, I don't think this non-forking model is going to work out. As I understand it, the forking model was abandoned due to cheating. However, non-forking takes up private repos that I don't have. So, I have to make the repos public, and we're back to square one.

**Comment by ksuderman** [comment]
@tarebyte I tried logging out and back in yesterday with no difference.  Today I deleted the classroom/assignment and recreated them and now it seems to be working.  Maybe something to do with the fact that the first time around the classroom name was the same as the organization name? 

However, I will run into the same problem as @khatchad; not enough private repos.  We have 25 students with 5 assignments, which will result in 125 repos plus the private repositories used for model solutions etc.  Do I request more private repositories by upgrading on the "Billing" page or should I send an email?

**Comment by tarebyte** [comment]
@ksuderman please send a request to https://github.com/contact and they will be able to help you get more free private repos.

**Comment by ksuderman** [comment]
Thanks @tarebyte I will do that.  I will let you close this issue when you've finished helping @khatchad.

**Comment by ksuderman** [comment]
It is happening again. See education/classroom#497, education/classroom#461, and education/classroom#445

Is there a central issue we should use to track this?

**Comment by johndbritton** [comment]
The root issue is https://github.com/education/classroom/issues/445. What's happening is teachers are testing out the application and accepting assignments. When you accept an assignment we ask for less account permissions than we do for teachers. If a teacher accepts an assignment, we reduce the access we have to their github accounts making it impossible for us to give their students access to the repos.

To resolve the issue, all teachers for the org have to log out and log back in on the main page https://education.github.com

This is a limitation of the way OAuth tokens work in the GitHub API and we're working on a permanent solution.
